all:
  children:

    rtp_wan_edge:
      hosts:
        csr1000v-1.sandbox.wwtatc.local: {}
        csr1000v-2.sandbox.wwtatc.local: {}
      vars:
        ansible_connection: network_cli
        ansible_network_os: ios
        ansible_become: yes
        ansible_become_method: enable
        ansible_ssh_user: admin
        # ansible_ssh_pass: can be set here or from encrypted vault file
        # See: https://stackoverflow.com/questions/30209062/ansible-how-to-encrypt-some-variables-in-an-inventory-file-in-a-separate-vault

    sample:
      hosts:
        localhost: {}

